# Generated by Django 4.1 on 2022-09-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapindi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('season_id', models.IntegerField()),
                ('winner_status', models.IntegerField()),
                ('vote', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=255)),
                ('school_name', models.CharField(max_length=50)),
                ('school_location', models.CharField(max_length=25)),
                ('subject_name', models.CharField(max_length=25)),
                ('class_name', models.CharField(max_length=255)),
                ('lesson', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video_id', models.CharField(max_length=15)),
                ('date_uploaded', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'mapindi',
            },
        ),
        migrations.CreateModel(
            name='MapindiSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=255)),
                ('open_close_status', models.IntegerField()),
                ('start_date', models.CharField(max_length=255)),
                ('end_date', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'mapindi_season',
            },
        ),
        migrations.CreateModel(
            name='MapindiUserVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('video_id', models.IntegerField()),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'mapindi_user_vote',
            },
        ),
        migrations.CreateModel(
            name='MapindiVideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('video_id', models.IntegerField()),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'mapindi_video_comment',
            },
        ),
    ]
